# JDBC settings
#yat.check.sql: 'select 1 from dual'
#yat.connection.autocommit: true

# Convert settings
#convert.result.meta.precision: false
#convert.result.meta.scale: false

# Yat system settings
# allow values 'strict' or 'smart'
#yat.compare.type: smart
#yat.compare.ignore.case: true
#yat.compare.disorder: true
#yat.compare.hash: false
#yat.testcase.out.suffix: ''
#yat.output.pretty: true

#yat.filling: '.'
#yat.txt.report.width: 100
yat.limit.case.count.max: 100000
#yat.limit.case.size.max: 15K
yat.limit.case.depth.max: 7
#yat.limit.case.name.pattern: '[a-zA-Z0-9_-]+'
